### ISSUE TITLE
More contracts than necessary are compiled when the contract is verified

### ISSUE THREAD

**Issue by fedgiac** [Tenderly/hardhat-tenderly#10]
I've been unable to verify some contracts on Tenderly using this plugin.
I believe the issue is caused by the fact that the Tenderly backend tries to compile more contract files than the the minimum necessary for verification. This means that the verification of a valid contract could fail because of an issue in an unused contract.

In my case, my project uses different Solc versions depending on which contracts are compiled. When verifying a contract compiled with Solc version `0.7.6`, Tenderly backend tries to compile another (unneeded) contract that requires Solc version `0.5.17`. The error returned from the server contains `Source file requires different compiler version (current compiler is 0.7.6+commit.7338295f.Linux.g++) - note that nightly builds are considered to be strictly less than the released version`.

This is how the issue can be reproduced:

```
$ git clone https://github.com/gnosis/gp-v2-contracts
$ git checkout reproduce-hardhat-tenderly-issue-multiple-solc-versions
$ yarn install
$ npx hardhat tenderly:verify --network rinkeby "GPv2Settlement=0x5b742f5b859829fdEF55d68e0A34e036844294bE"
Error in hardhat-tenderly: There was an error during the request. Contract verification failed
$ rm src/contracts/test/GnosisSafeERC1271Fallback.sol
$ npx hardhat tenderly:verify --network rinkeby "GPv2Settlement=0x5b742f5b859829fdEF55d68e0A34e036844294bE"
Smart Contracts successfully verified
  Contract 0x5b742f5b859829fdef55d68e0a34e036844294be verified. You can view the contract at https://dashboard.tenderly.co/contract/rinkeby/0x5b742f5b859829fdef55d68e0a34e036844294be
```

Note that verification is successful after removing the source file for a contract.

**Comment by Malcador** [comment]
Hey, thanks for the report and detailed reproduction instructions, it means a lot. I've updated it to only take the required contracts in [this](https://github.com/Tenderly/hardhat-tenderly/commit/c08516abb4693cd6bf5b1a6b838353bd0282af93) commit. We'll take a look at the network issue as well, and let you know when a new version is released.

**Comment by Malcador** [comment]
To follow up on this, I've just released a new version with the fixed contract verification. As for the networks, that's pending some more discussion on how to best handle it, so I'll let you know in the other thread.

The version with the proper verification is 1.0.11
