### ISSUE TITLE
 Network of contract verification based on config name instead of network id

### ISSUE THREAD

**Issue by fedgiac** [Tenderly/hardhat-tenderly#11]
The verification script chooses the network in which to verify the contract depending on the network name specified in the command line parameter `--network`, which is chosen by the user in `hardhat.config.ts`. This name is mapped to a network ID using a hardcoded list from this repo. If the name of the network is not in this list, the network to verify is set to `undefined` and verification fails with a generic error.

This is an issue when the same network is used in multiple configurations, for example `mainnet-dev`, `mainnet-prod`.
It's also particularly noticeable when the network is xDai: in this project it's spelled `xDai` (capital D) while in my project it was spelled `xdai`.

This is the behavior I'd expect:
- The network chosen for verification on Tenderly should be based on the network ID. Currently, it's based on the name of the network in the Hardhat configurations.
- If the network is not supported by Tenderly, the verification plugin should tell me that the network is not supported. Currently, it fails with a generic message at a later step.

A related issue: the link that appears on successful verification is built from the network name. The link to a contract on the xDai network uses the capitalized version, which produces a broken link to Tenderly (the correct link uses a fully lowercase `xdai`).

**Comment by Malcador** [comment]
This has been resolved as of v1.0.12, it will now map networks by chainID first, falling back to the network slugs in case the chainID is missing.
