### ISSUE TITLE
Tenderly freeze hardhat console

### ISSUE THREAD

**Issue by Shelvak** [Tenderly/hardhat-tenderly#16]
I'm trying to get tenderly working with hardhat to verify my contracts in mumbai. But I can't get it working.

Inside hardhat console I start typing `hre` and the console freeze and the CPU goes to 100~110%
![Captura de pantalla de 2021-05-18 16-03-26](https://user-images.githubusercontent.com/873323/118708933-b9aca480-b7f2-11eb-8407-8a93ae041c5c.png)

Without `require("@tenderly/hardhat-tenderly");` line in my hardhat.config.js it doesn't happen.

After 1~1.5 minutes that unfreeze but after I hit just one more character it happens again.

I can't get it verified after the freeze time, I tried from CLI and from hardhat console, the same result:
`> await hre.tenderly.verify({name: 'Vault', address: vault.address})`
![imagen](https://user-images.githubusercontent.com/873323/118710677-ff6a6c80-b7f4-11eb-9369-420ab7fe61ac.png)

Other thing is that in readme you use `bre` but it's not available, only hre.

Hardhat version: 2.2.1
hardhat-tenderly version: 1.0.12
tenderly version: 1.0.1
tenderly command is logged in (with ~/.tenderly/config.yml)

package.json:
[package.txt](https://github.com/Tenderly/hardhat-tenderly/files/6503708/package.txt)
hardhat.config.js:
[hardhat.config.txt](https://github.com/Tenderly/hardhat-tenderly/files/6503709/hardhat.config.txt)

**Comment by BogdanHabic** [comment]
Hey!

I must admit I think we never tried it via the hardhat console. Does the same thing happen when you're invoking other hardhat commands?

**Comment by Shelvak** [comment]
Hi Bogdan, no, it happens only with autocomplete/suggest on console. Any thoughts in the `There was an error during the request. Contract verification failed` error?

**Comment by BogdanHabic** [comment]
Are you pushing/verifying a local network or something that is deployed to a live network?

**Comment by Shelvak** [comment]
Tried both push and verify to mumbai (polygon testnet) and the contract is already deployed.

**Comment by BogdanHabic** [comment]
We caught what the issue was for the CPU usage problem. We'll cook up a fix and let you know once it is live!

**Comment by Shelvak** [comment]
Amazing Bogdan, thank you :+1:

**Comment by Malcador** [comment]
We've looked into it a bit more, looks like it's an issue with Hardhat itself. You can continue tracking the issue over [here](https://github.com/nomiclabs/hardhat/issues/1473) if you'd like.
