### ISSUE TITLE
Pushing contracts to Tenderly doesn't pick up project & username from the tenderly config

### ISSUE THREAD

**Issue by dimpar** [Tenderly/hardhat-tenderly#20]
Contracts are not added to the project specified in the [tenderly config](https://github.com/Tenderly/hardhat-tenderly/issues/17) for an authenticated user. When pushing to Tenderly the link that is being created is following: `https://dashboard.tenderly.co/contract/ropsten/0x1e83039a7f14d035ec0de7cfd9044a24860ce14a` instead of `https://dashboard.tenderly.co/<username>/<project>/0x1e83039a7f14d035ec0de7cfd9044a24860ce14a`

**Comment by BogdanHabic** [comment]
Verify does public verification without actually adding the contract to a project. We will add an optional param that will tell the API to add it to a project.

**Comment by dule-git** [comment]
Hey @dimpar,

I'll close this issue since automatic verification and `hre.tenderly.verify` now add the verified contract to the project if the verification is private. 😄
