### ISSUE TITLE
CryptoSlug | Tenderly

### ISSUE THREAD

**Issue by CryptonightCanada** [Tenderly/hardhat-tenderly#24]
https://dashboard.tenderly.co/CryptoNightCA/cryptoslug/transactions?addresses=1%3A0xff03bd63523e6fd7b50cf73c6cc165f0317663e6

**Comment by dule-git** [comment]
Hey @CryptonightCanada,

Thanks for sharing the link to your Tenderly transaction that I don't have access to! 😄

I'll close the issue since I don't have enough information to work on it.
Feel free to reopen the issue and provide more details.
