### ISSUE TITLE
#### Review or Edit in CodeSandbox

### ISSUE THREAD

**Issue by ibrahimkhled** [Tenderly/hardhat-tenderly#244]
#### Review or Edit in CodeSandbox

Open the branch in <a href="https://codesandbox.io/p/github/ibrahimkhled/ibrahimkhled/revert-1-ibrahimkhled-patch-1?mode=review&utm_source=gh_app">Web Editor</a> &bull; <a href="https://codesandbox.io/p/vscode?owner=ibrahimkhled&repo=ibrahimkhled&branch=revert-1-ibrahimkhled-patch-1&utm_source=gh_app">VS Code</a> &bull; <a href="https://codesandbox.io/p/vscode?owner=ibrahimkhled&repo=ibrahimkhled&branch=revert-1-ibrahimkhled-patch-1&insiders=true&utm_source=gh_app">Insiders</a><br>
Open <a href="https://codesandbox.io/p/devtool/preview/ibrahimkhled/ibrahimkhled/revert-1-ibrahimkhled-patch-1?task=preview&port=51423&redirect=true&utm_source=gh_app">Preview</a>

_Originally posted by @codesandbox in https://github.com/ibrahimkhled/ibrahimkhled/pull/2#issuecomment-2245054419_

**Comment by dule-git** [comment]
I have few information and the issue hasn't been described well.
All the links I have opened are either empty or not able to open, thus I'll close the issue. 😄
