### ISSUE TITLE
hardhat-tenderly: No new contracts have been verified

### ISSUE THREAD

**Issue by Thanasornsawan** [Tenderly/hardhat-tenderly#28]
I run sample script on hardhat-tenderly typescript.It cannot push and verify contract on localhost network and show no new contact has been verified.

Result in console show
```
user@DESKTOP:/mnt/c/Users/Documents/hardhat-typescript$ npx hardhat run scripts/deploy.ts --network localhost
No need to generate any newer typings.
Greeter deployed to:  0x4A679253410272dd5232B3Ff7cF5dbB88f295319
Greeter transaction hash:  0xf860ea06dc4580dc6c5584360b09a3558e0d56b58c45022a23e31586de46f2f8
Counter deployed to:  0x7a2088a1bFc9d81c55368AE168C2C02570cB814F
Counter transaction hash:  0xc4c99ab8a2f711ee7fb93ba9862d6e9bb61e417d90f3f89281b73c50f10f7ab8
hardhat-tenderly: No new contracts have been verified
```

The code is 
```
import { ethers, tenderly } from "hardhat";
//import {HardhatRuntimeEnvironment} from 'hardhat/types';

async function main() {

  const Greeter = await ethers.getContractFactory("Greeter");
  const greeter = await Greeter.deploy("Hello, Hardhat!");
  await greeter.deployed();

  console.log("Greeter deployed to: ", greeter.address);
  console.log("Greeter transaction hash: ",greeter.deployTransaction.hash);

  const Counter = await ethers.getContractFactory("Counter");
  const counter = await Counter.deploy();
  await counter.deployed();

  console.log("Counter deployed to: ", counter.address);
  console.log("Counter transaction hash: ", counter.deployTransaction.hash);

  let artifact = await tenderly.persistArtifacts({
    name: "Greeter",
    address: greeter.address
  });

  let verification = await tenderly.verify({
    name: "Greeter",
    address: greeter.address,
  });
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
```

My repo is here if want to see hardhat.config [github](https://github.com/Thanasornsawan/hardhat-typechain/)

**Comment by BogdanHabic** [comment]
Hey, I see you closed the issue: I just wanted to check if you managed to resolve your issue (no support for local networks).

**Comment by Thanasornsawan** [comment]
> Hey, I see you closed the issue: I just wanted to check if you managed to resolve your issue (no support for local networks).

Yes i manage to solve my issue and public my note here https://github.com/Thanasornsawan/hardhat-typechain

The reason of that error when deploy tenderly script via localhost. Tenderly not find chainID to verify even config on hardhat config but it works when use testnet and mainnet. That error will gone and if want to use localhost. It need to done by tenderly-cli instread.

**Comment by BogdanHabic** [comment]
Hey @WXF-WangXuFeng, this isn't a problem, as in Tenderly isn't designed to have local contracts added to it.

If you want to debug local txs, you can by using the [export command](https://docs.tenderly.co/monitoring/integrations#debug-and-profile-local-transactions-with-tenderly-export).
