### ISSUE TITLE
Compiler version is inconstistent

### ISSUE THREAD

**Issue by RilRil** [Tenderly/hardhat-tenderly#29]
Hi ! not sure the issue is coming from this plugin exactly but you might be able to help.
When trying to debug a transaction and doing `tenderly export --debug --force <tx_hash>` 
I get this error 
```
Trying Hardhat config path: /Users/dev/project/hardhat.config.js
[          ] Making request
[======    ] Got response with body
api error exporting transaction: invalid_compiler_version
Compiler version is inconsistent
```

and here is the solidity part of my hardhat.config.js
```
  solidity: {
    compilers: [
      {
        version: "0.5.1",
        settings: { optimizer: { enabled: false, runs: 200 } }
      },
      { version: "0.5.16" },
      {
        version: "0.6.6",
        settings: { optimizer: { enabled: true, runs: 1000 } }
      },
      {
        version: "0.7.6",
        settings: { optimizer: { enabled: false, runs: 200 } }
      }
    ]
  },
```

Do you have any idea of what could cause this ? I didn't found anything related to this in the docs..
thanks in advance

**Comment by dule-git** [comment]
Hey @RilRil,

`tenderly export` has been deprecated and we are not supporting it anymore.
For verification flows, you can use this plugin or verify the contracts on Tenderly with Foundry.
