### ISSUE TITLE
Plugin does not respect custom hardhat deployment folder with persistArtifacts

### ISSUE THREAD

**Issue by CodeForcer** [Tenderly/hardhat-tenderly#31]
In the plugin code the deployment folder is always locked to `deployments`:
```
const destPath = `deployments${path_1.sep}${network.toLowerCase()}_${chainID}${path_1.sep}`;
```

This causes various bugs due to Tenderly behaviour of always trying to gather and upload all files in deployments folder

**Comment by pvdyck** [comment]
Confirmed / Any solution ?

**Comment by filippetroviccc** [comment]
In the new version (v1.1.2) you can specify the location of the deployments dir. 

https://github.com/Tenderly/hardhat-tenderly#configuration
```
module.exports = {
    tenderly: {
        project: "",
        username: "",
        // forkNetwork: "",
        // privateVerification: false,
        // deploymentsDir: "deployments"
    }
};
```
