### ISSUE TITLE
introduction of `forkNetwork` deserves a major release

### ISSUE THREAD

**Issue by flipdazed** [Tenderly/hardhat-tenderly#47]
The inclusion of `forkNetwork` breaks tenderly configs that omit `forkNetwork` in `hardhat.config.ts`

Given that most users will use the carat symbol, the breaking behaviour of the introduction of of `forkNetwork` is probably more appropriate with a major version release.

Note that in `package.json`
```json
"@tenderly/hardhat-tenderly": ^1.0.0
```
will currently pick up

```json
"@tenderly/hardhat-tenderly": ^1.1.0
```

This will fail to compile for any users that configured using `<1.1.0` with

```bash
Property 'forkNetwork' is missing in type '{ project: string; username: string; }' but required in type 'TenderlyConfig'.  
```

**Comment by filippetroviccc** [comment]
Hey @flipdazed 

It was never intended to introduce a breaking change, sorry if this caused any inconvenience. 
In version `v1.1.1` it is no longer needed in the `TenderlyConfig`. 

PR #48
