### ISSUE TITLE
dependency issue with hardhat-deploy-ethers

### ISSUE THREAD

**Issue by samlaf** [Tenderly/hardhat-tenderly#51]
See this issue that I opened in hardhat-deploy-ethers: https://github.com/wighawag/hardhat-deploy-ethers/issues/26

the creator of hardhat-deploy-ethers suggests that hardhat-tenderly does not [hardcode its version of hardhat-ethers](https://github.com/Tenderly/hardhat-tenderly/blob/69566c4c55c0d6292c1e3770fa46dd52e5201c1e/package.json#L54), to prevent such issues (hardhat-deploy-ethers is a fork of hardhat-ethers).

**Comment by iantanwx** [comment]
we are also blocked on this. it looks like moving `@nomiclabs/hardhat-ethers` to `peerDependencies` is sufficient. I will fork and test this later.

**Comment by iantanwx** [comment]
@samlaf adding the following to `package.json` works for `yarn`:

```
  "resolutions": {
    "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.3.0-beta.13"
  }
  ```
See the [yarn docs on `resolutions`](https://yarnpkg.com/configuration/manifest#resolutions) for more. For `npm`, the equivalent is [`overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides).

**Comment by samlaf** [comment]
Oh wow ok I’ll give it a try when I get back to this project. Thanks :)

**Comment by fvictorio** [comment]
> It looks like moving @nomiclabs/hardhat-ethers to peerDependencies is sufficient

Agree. Also worth mentioning that this is [one of our recommended practices](https://hardhat.org/hardhat-runner/docs/advanced/building-plugins#notes-on-dependencies) when building Hardhat plugins.

**Comment by sebastiantf** [comment]
`tsc` complaining several `Duplicate identifier` errors with `@nomiclabs/hardhat-ethers`


> samlaf adding the following to `package.json` works for `yarn`:
> 
> ```
>   "resolutions": {
>     "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.3.0-beta.13"
>   }
> ```
> 
> See the [yarn docs on `resolutions`](https://yarnpkg.com/configuration/manifest#resolutions) for more. For `npm`, the equivalent is [`overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides).

This resolved it for now

**Comment by matthewlilley** [comment]
> @samlaf adding the following to `package.json` works for `yarn`:
> 
> ```
>   "resolutions": {
>     "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.3.0-beta.13"
>   }
> ```
> 
> See the [yarn docs on `resolutions`](https://yarnpkg.com/configuration/manifest#resolutions) for more. For `npm`, the equivalent is [`overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides).

For those using PNPM

```
  "pnpm": {
    "overrides": {
      "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.3.0-beta.13"
    }
  },
```

**Comment by dule-git** [comment]
Hi all, 

Since all of you have found workarounds and this was long time ago, I'll close the issue.

Please fill free to reopen it if you are still having problems.
